$(call setup-stamp-file,FTST_FUNCTIONAL_TESTS_STAMP,/functional-tests)

FTST_DIR := $(BUILDDIR)/tmp/functional-tests
FTST_TEST_TMP := $(FTST_DIR)/test-tmp
FTST_IMAGE_DIR := $(FTST_DIR)/image
FTST_IMAGE_ROOTFSDIR := $(FTST_IMAGE_DIR)/rootfs
FTST_IMAGE := $(FTST_DIR)/rkt-inspect.aci
FTST_IMAGE_MANIFEST_SRC := $(MK_SRCDIR)/image/manifest
FTST_IMAGE_MANIFEST := $(FTST_IMAGE_DIR)/manifest
FTST_IMAGE_TEST_DIRS := $(FTST_IMAGE_ROOTFSDIR)/dir1 $(FTST_IMAGE_ROOTFSDIR)/dir2
FTST_ACE_MAIN_IMAGE_DIR := $(FTST_DIR)/ace-main
FTST_ACE_MAIN_IMAGE_ROOTFSDIR := $(FTST_ACE_MAIN_IMAGE_DIR)/rootfs
FTST_ACE_MAIN_IMAGE := $(FTST_DIR)/rkt-ace-validator-main.aci
FTST_ACE_MAIN_IMAGE_MANIFEST_SRC := Godeps/_workspace/src/github.com/appc/spec/ace/image_manifest_main.json
FTST_ACE_MAIN_IMAGE_MANIFEST := $(FTST_ACE_MAIN_IMAGE_DIR)/manifest
FTST_ACE_SIDEKICK_IMAGE_DIR := $(FTST_DIR)/ace-sidekick
FTST_ACE_SIDEKICK_IMAGE_ROOTFSDIR := $(FTST_ACE_SIDEKICK_IMAGE_DIR)/rootfs
FTST_ACE_SIDEKICK_IMAGE := $(FTST_DIR)/rkt-ace-validator-sidekick.aci
FTST_ACE_SIDEKICK_IMAGE_MANIFEST_SRC := Godeps/_workspace/src/github.com/appc/spec/ace/image_manifest_sidekick.json
FTST_ACE_SIDEKICK_IMAGE_MANIFEST := $(FTST_ACE_SIDEKICK_IMAGE_DIR)/manifest
FTST_INSPECT_BINARY := $(FTST_DIR)/inspect
FTST_ACI_INSPECT := $(FTST_IMAGE_ROOTFSDIR)/inspect
FTST_ACE_BINARY := $(FTST_DIR)/ace-validator
FTST_ACI_MAIN_ACE_BINARY := $(FTST_ACE_MAIN_IMAGE_ROOTFSDIR)/ace-validator
FTST_ACI_SIDEKICK_ACE_BINARY := $(FTST_ACE_SIDEKICK_IMAGE_ROOTFSDIR)/ace-validator
FTST_ECHO_SERVER_BINARY := $(FTST_DIR)/echo-socket-activated
FTST_ACI_ECHO_SERVER := $(FTST_IMAGE_ROOTFSDIR)/echo-socket-activated
FTST_EMPTY_IMAGE_DIR := $(FTST_DIR)/empty-image
FTST_EMPTY_IMAGE_ROOTFSDIR := $(FTST_EMPTY_IMAGE_DIR)/rootfs
FTST_EMPTY_IMAGE := $(FTST_DIR)/rkt-empty.aci
FTST_EMPTY_IMAGE_MANIFEST_SRC := $(MK_SRCDIR)/empty-image/manifest
FTST_EMPTY_IMAGE_MANIFEST := $(FTST_EMPTY_IMAGE_DIR)/manifest

TOPLEVEL_CHECK_STAMPS += $(FTST_FUNCTIONAL_TESTS_STAMP)
INSTALL_FILES += $(FTST_IMAGE_MANIFEST_SRC):$(FTST_IMAGE_MANIFEST):- $(FTST_INSPECT_BINARY):$(FTST_ACI_INSPECT):- $(FTST_EMPTY_IMAGE_MANIFEST_SRC):$(FTST_EMPTY_IMAGE_MANIFEST):- $(FTST_ACE_MAIN_IMAGE_MANIFEST_SRC):$(FTST_ACE_MAIN_IMAGE_MANIFEST):- $(FTST_ACE_SIDEKICK_IMAGE_MANIFEST_SRC):$(FTST_ACE_SIDEKICK_IMAGE_MANIFEST):- $(FTST_ECHO_SERVER_BINARY):$(FTST_ACI_ECHO_SERVER):-
CREATE_DIRS += $(FTST_DIR) $(FTST_IMAGE_DIR) $(FTST_IMAGE_ROOTFSDIR) $(FTST_EMPTY_IMAGE_DIR) $(FTST_EMPTY_IMAGE_ROOTFSDIR) $(FTST_ACE_MAIN_IMAGE_DIR) $(FTST_ACE_MAIN_IMAGE_ROOTFSDIR) $(FTST_ACE_SIDEKICK_IMAGE_DIR) $(FTST_ACE_SIDEKICK_IMAGE_ROOTFSDIR) $(FTST_IMAGE_TEST_DIRS) $(FTST_TEST_TMP)
CLEAN_FILES += $(FTST_IMAGE)

$(FTST_FUNCTIONAL_TESTS_STAMP): RKT := $(RKT_BINARY)
$(FTST_FUNCTIONAL_TESTS_STAMP): ACTOOL := $(ACTOOL)
$(FTST_FUNCTIONAL_TESTS_STAMP): FTST_IMAGE := $(FTST_IMAGE)
$(FTST_FUNCTIONAL_TESTS_STAMP): FTST_EMPTY_IMAGE := $(FTST_EMPTY_IMAGE)
$(FTST_FUNCTIONAL_TESTS_STAMP): FTST_TEST_TMP := $(FTST_TEST_TMP)
$(FTST_FUNCTIONAL_TESTS_STAMP): ABS_GO := $(ABS_GO)
$(FTST_FUNCTIONAL_TESTS_STAMP): GO_ENV := $(GO_ENV)
$(FTST_FUNCTIONAL_TESTS_STAMP): FTST_INSPECT_BINARY := $(FTST_INSPECT_BINARY)
# GO_TEST_FUNC_ARGS deliberately not copied into rule
$(FTST_FUNCTIONAL_TESTS_STAMP): REPO_PATH := $(REPO_PATH)
$(FTST_FUNCTIONAL_TESTS_STAMP): $(FTST_IMAGE) $(FTST_EMPTY_IMAGE) $(FTST_ACE_MAIN_IMAGE) $(FTST_ACE_SIDEKICK_IMAGE) $(ACTOOL_STAMP) $(RKT_STAMP) | $(FTST_TEST_TMP)
	sudo RKT="$(RKT)" ACTOOL="$(ACTOOL)" RKT_INSPECT_IMAGE="$(FTST_IMAGE)" RKT_EMPTY_IMAGE="$(FTST_EMPTY_IMAGE)" RKT_ACE_MAIN_IMAGE=$(FTST_ACE_MAIN_IMAGE) RKT_ACE_SIDEKICK_IMAGE=$(FTST_ACE_SIDEKICK_IMAGE) FUNCTIONAL_TMP="$(FTST_TEST_TMP)" GO="$(ABS_GO)" INSPECT_BINARY="$(FTST_INSPECT_BINARY)" $(GO_ENV) "$(ABS_GO)" test -timeout 20m -v $(GO_TEST_FUNC_ARGS) $(REPO_PATH)/tests

$(FTST_IMAGE): ACTOOL := $(ACTOOL)
$(FTST_IMAGE): FTST_IMAGE_DIR := $(FTST_IMAGE_DIR)
$(FTST_IMAGE): FTST_IMAGE_ROOTFSDIR := $(FTST_IMAGE_ROOTFSDIR)
$(FTST_IMAGE): $(FTST_IMAGE_MANIFEST) $(FTST_ACI_INSPECT)  $(FTST_ACI_ECHO_SERVER) | $(FTST_IMAGE_TEST_DIRS)
	echo -n dir1 >$(FTST_IMAGE_ROOTFSDIR)/dir1/file
	echo -n dir2 >$(FTST_IMAGE_ROOTFSDIR)/dir2/file
	"$(ACTOOL)" build --overwrite "$(FTST_IMAGE_DIR)" "$@"

BGB_BINARY := $(FTST_INSPECT_BINARY)
BGB_PKG_IN_REPO := $(subst $(MK_TOPLEVEL_SRCDIR)/,,$(MK_SRCDIR))/inspect
BGB_GO_FLAGS := -a -installsuffix cgo
BGB_ADDITIONAL_GO_ENV := CGO_ENABLED=0

include makelib/build_go_bin.mk

BGB_BINARY := $(FTST_ACE_BINARY)
BGB_PKG_IN_REPO := Godeps/_workspace/src/github.com/appc/spec/ace
BGB_GO_FLAGS := -a -installsuffix cgo
BGB_ADDITIONAL_GO_ENV := CGO_ENABLED=0

include makelib/build_go_bin.mk

$(FTST_EMPTY_IMAGE): ACTOOL := $(ACTOOL)
$(FTST_EMPTY_IMAGE): FTST_EMPTY_IMAGE_DIR := $(FTST_EMPTY_IMAGE_DIR)
$(FTST_EMPTY_IMAGE): $(FTST_EMPTY_IMAGE_MANIFEST) | $(FTST_EMPTY_IMAGE_ROOTFSDIR)
	"$(ACTOOL)" build --overwrite "$(FTST_EMPTY_IMAGE_DIR)" "$@"

BGB_BINARY := $(FTST_ECHO_SERVER_BINARY)
BGB_PKG_IN_REPO := $(subst $(MK_TOPLEVEL_SRCDIR)/,,$(MK_SRCDIR))/echo-socket-activated
BGB_GO_FLAGS := -a -installsuffix cgo
BGB_ADDITIONAL_GO_ENV := CGO_ENABLED=0

include makelib/build_go_bin.mk

# 1 - image
# 2 - aci directory
# 3 - ace validator
define ftst-generate-ace-image
$1: ACTOOL := $$(ACTOOL)
$1: $2/manifest $2/rootfs/ace-validator | $2/rootfs
	mkdir -p $2/rootfs/opt/acvalidator
	# Set a consistent timestamp so we get a consistent hash
	# TODO(jonboulle): make this cleaner..
	for path in "$2/rootfs" $2/rootfs/ace-validator; do \
		touch -a -m -d 1970-01-01T00:00:00Z "$$$${path}"; \
	done
	"$(ACTOOL)" build --overwrite "$2" "$1"

CREATE_DIRS += $2 $2/rootfs
INSTALL_FILES += $3:$2/rootfs/ace-validator:-
endef

$(eval $(call ftst-generate-ace-image,$(FTST_ACE_MAIN_IMAGE),$(FTST_ACE_MAIN_IMAGE_DIR),$(FTST_ACE_BINARY)))
$(eval $(call ftst-generate-ace-image,$(FTST_ACE_SIDEKICK_IMAGE),$(FTST_ACE_SIDEKICK_IMAGE_DIR),$(FTST_ACE_BINARY)))

FTST_FUNCTIONAL_TESTS_STAMP :=

FTST_DIR :=
FTST_IMAGE_DIR :=
FTST_IMAGE_ROOTFSDIR :=
FTST_IMAGE :=
FTST_IMAGE_MANIFEST_SRC :=
FTST_IMAGE_MANIFEST :=
FTST_IMAGE_TEST_DIRS :=
FTST_INSPECT_BINARY :=
FTST_ACI_INSPECT :=
FTST_ECHO_SERVER_BINARY :=
FTST_ACI_ECHO_SERVER :=
FTST_EMPTY_IMAGE_DIR :=
FTST_EMPTY_IMAGE_ROOTFSDIR :=
FTST_EMPTY_IMAGE :=
FTST_EMPTY_IMAGE_MANIFEST_SRC :=
FTST_EMPTY_IMAGE_MANIFEST :=
